const testBets = [
  {
    Title: 'VoteFor1',
    Description: 'This is a description for the vote',
    Creator: 'address',
    Challenger: 'address',
    BetStartDate: 'UTC',
    BetEndDate: 'UTC',
    WaitingForChallengerExpiration: 'UTC',
    AwaitingVotesExpiration: 'UTC',
    VotesForCreator: 0,
    VotesForChallenger: 0,
    CreatorSurrender: false,
    ChallengerSurrender: false,
    ActiveBetPeriod: false,
    AwaitingVotesPeriod: false,
    BetCompleted: false,
    ChallengerAdded: false,
    BetAmount: 0,
    BetWinner: 'address',
    BetEscrow: 'address',
  },
  {
    Title: 'VoteFor2',
    Description: 'This is a description for the vote1',
    Creator: 'address',
    Challenger: 'address',
    BetStartDate: 'UTC',
    BetEndDate: 'UTC',
    WaitingForChallengerExpiration: 'UTC',
    AwaitingVotesExpiration: 'UTC',
    VotesForCreator: 0,
    VotesForChallenger: 0,
    CreatorSurrender: false,
    ChallengerSurrender: false,
    ActiveBetPeriod: false,
    AwaitingVotesPeriod: false,
    BetCompleted: false,
    ChallengerAdded: false,
    BetAmount: 0,
    BetWinner: 'address',
    BetEscrow: 'address',
  },
  {
    Title: 'VoteFor3',
    Description: 'This is a description for the vote2',
    Creator: 'address',
    Challenger: 'address',
    BetStartDate: 'UTC',
    BetEndDate: 'UTC',
    WaitingForChallengerExpiration: 'UTC',
    AwaitingVotesExpiration: 'UTC',
    VotesForCreator: 0,
    VotesForChallenger: 0,
    CreatorSurrender: false,
    ChallengerSurrender: false,
    ActiveBetPeriod: false,
    AwaitingVotesPeriod: false,
    BetCompleted: false,
    ChallengerAdded: false,
    BetAmount: 0,
    BetWinner: 'address',
    BetEscrow: 'address',
  },
  {
    Title: 'VoteFor3',
    Description: 'This is a description for the vote3',
    Creator: 'address',
    Challenger: 'address',
    BetStartDate: 'UTC',
    BetEndDate: 'UTC',
    WaitingForChallengerExpiration: 'UTC',
    AwaitingVotesExpiration: 'UTC',
    VotesForCreator: 0,
    VotesForChallenger: 0,
    CreatorSurrender: false,
    ChallengerSurrender: false,
    ActiveBetPeriod: false,
    AwaitingVotesPeriod: false,
    BetCompleted: false,
    ChallengerAdded: false,
    BetAmount: 0,
    BetWinner: 'address',
    BetEscrow: 'address',
  },
  {
    Title: 'VoteFor4',
    Description: 'This is a description for the vote4',
    Creator: 'address',
    Challenger: 'address',
    BetStartDate: 'UTC',
    BetEndDate: 'UTC',
    WaitingForChallengerExpiration: 'UTC',
    AwaitingVotesExpiration: 'UTC',
    VotesForCreator: 0,
    VotesForChallenger: 0,
    CreatorSurrender: false,
    ChallengerSurrender: false,
    ActiveBetPeriod: false,
    AwaitingVotesPeriod: false,
    BetCompleted: false,
    ChallengerAdded: false,
    BetAmount: 0,
    BetWinner: 'address',
    BetEscrow: 'address',
  },
];
export default testBets;
